"""
Django settings for suavespets project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv
import pymysql
pymysql.install_as_MySQLdb()

load_dotenv(find_dotenv())

DOG_API_KEY = os.getenv('DOG_API_KEY')
CAT_API_KEY = os.getenv('CAT_API_KEY')

DATABASE_URL = os.getenv('DATABASE_URL')



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: se lee desde variables de entorno
# Usa `SECRET_KEY` y `DEBUG` configuradas en el entorno (Render/Local)

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'suavespets.onrender.com').split(',')




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appsuavespets',
    'sslserver',
    'django_extensions',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'suavespets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'suavespets.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def env_bool(name, default=False):
    val = os.getenv(name)
    return (str(val).lower() in ('1', 'true', 'yes')) if val is not None else default

DB_OPTIONS = {
    "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
    "charset": "utf8mb4",
}

if env_bool('DB_USE_SSL', False):
    ssl_cfg = {
        'check_hostname': False,
        'verify_cert': False,
    }
    if os.getenv('DB_SSL_CA'):
        ssl_cfg['ca'] = os.getenv('DB_SSL_CA')
    if os.getenv('DB_SSL_CERT'):
        ssl_cfg['cert'] = os.getenv('DB_SSL_CERT')
    if os.getenv('DB_SSL_KEY'):
        ssl_cfg['key'] = os.getenv('DB_SSL_KEY')
    DB_OPTIONS['ssl'] = ssl_cfg

USE_SQLITE = env_bool('DB_USE_SQLITE', False) or (os.getenv('DB_NAME') is None)

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASS'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': DB_OPTIONS,
        }
    }


# Supongamos que defines la variable de entorno DJANGO_DEBUG para controlar el entorno
import os

# Definir DEBUG mediante variable de entorno para distinguir entorno desarrollo/producción
# Esto permite que las configuraciones HTTPS solo se apliquen en producción
DEBUG = os.getenv('DEBUG', 'False') == 'True'


if not DEBUG:
    # Configuraciones para producción: forzar HTTPS y seguridad adicional
    SESSION_COOKIE_SECURE = True         # La cookie de sesión solo se envía con HTTPS
    CSRF_COOKIE_SECURE = True            # La cookie CSRF solo se envía con HTTPS
    SECURE_SSL_REDIRECT = True           # Redirige automáticamente todas las peticiones HTTP a HTTPS
    SECURE_HSTS_SECONDS = 3600           # HSTS: indica a browsers usar solo HTTPS por 1 hora
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True     # Habilita filtro XSS del navegador
    SECURE_CONTENT_TYPE_NOSNIFF = True   # Previene ataques de tipo MIME sniffing
    X_FRAME_OPTIONS = 'DENY'              # Evita que la página sea renderizada en frames (clickjacking)
else:
    # En desarrollo no forzamos HTTPS para evitar problemas sin certificado
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'       # Permite framing en desarrollo local




# Duración de sesión (ejemplo: 20 minutos)
SESSION_COOKIE_AGE = 20 * 60

# Indica si la sesión debe expirar al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# URL para login automático si el usuario no está autenticado
LOGIN_URL = '/login/'

# Motor para almacenar sesiones (base de datos por defecto, seguro y persistente)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


SECRET_KEY = os.getenv('SECRET_KEY')


AUTH_USER_MODEL = 'appsuavespets.Usuario'

# Backend de autenticación (si usas email para login)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Redirecciones después de login/logout
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'listado_pets'
LOGOUT_REDIRECT_URL = 'inicio'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]




SESSION_COOKIE_AGE = 7200 
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
