# Generated by Django 5.2.8 on 2025-12-02 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVeterinario',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True)),
                ('requiere_receta', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'producto_veterinario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('identificacion', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_usuario', models.CharField(default='invitado', max_length=20)),
                ('cuota_activa', models.BooleanField(default=False)),
                ('fecha_vencimiento_cuota', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('operacion', models.CharField(max_length=6)),
                ('registro_id', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_operacion', models.DateTimeField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventoClinico',
            fields=[
                ('id_eventoclinico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateField()),
                ('tipo_evento', models.CharField(max_length=20)),
                ('sintomas_reportados', models.TextField()),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('estado_preconsulta', models.CharField(blank=True, max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('id_usuario_responsable', models.ForeignKey(db_column='id_usuario_responsable', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evento_clinico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo_url', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_eventoclinico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appsuavespets.eventoclinico')),
            ],
            options={
                'db_table': 'archivo_adjunto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pet', models.CharField(max_length=50)),
                ('descripcion_pet', models.TextField()),
                ('especie', models.CharField(max_length=10)),
                ('tamanio', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=100)),
                ('es_mestizo', models.IntegerField()),
                ('otra_raza', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('numero_ficha', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('psvpet_dos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet_psvpet_dos_set', to=settings.AUTH_USER_MODEL)),
                ('psvpet_uno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet_psvpet_uno_set', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet_veterinario_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('leido', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appsuavespets.pet')),
            ],
            options={
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='id_pet',
            field=models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.DO_NOTHING, to='appsuavespets.pet'),
        ),
        migrations.CreateModel(
            name='Cuidados',
            fields=[
                ('id_cuidado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cuidado', models.CharField(max_length=50)),
                ('fecha_proxima', models.DateField()),
                ('dosis', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.DO_NOTHING, to='appsuavespets.pet')),
            ],
            options={
                'db_table': 'cuidados',
                'managed': True,
            },
        ),
    ]
