# Generated by Django 5.2.8 on 2025-12-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
