# Generated by Django 5.2.8 on 2025-12-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
