# Generated by Django 5.2.8 on 2025-12-02 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0003_remove_usuario_id_usuario_dni_usuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id_pet',
            field=models.AutoField(db_column='id_pet', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='psvpet_dos',
            field=models.ForeignKey(blank=True, db_column='psvpet_dos_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet_psvpet_dos_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='psvpet_uno',
            field=models.ForeignKey(blank=True, db_column='psvpet_uno_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet_psvpet_uno_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='responsable',
            field=models.ForeignKey(blank=True, db_column='responsable_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='veterinario',
            field=models.ForeignKey(blank=True, db_column='veterinario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet_veterinario_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
