# Generated by Django 5.2.8 on 2025-12-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0004_alter_pet_id_pet_alter_pet_psvpet_dos_and_more'),
    ]

    operations = []
