# Generated by Django 5.2.8 on 2025-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0005_alter_pet_options_remove_pet_alergias_and_more'),
    ]

    operations = []
