# Generated by Django 5.2.8 on 2025-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0006_alter_pet_options_remove_pet_alergias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='id_pet',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='numero_ficha',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='otra_raza',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='psvpet_dos',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='psvpet_uno',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='veterinario',
        ),
        migrations.AddField(
            model_name='pet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='descripcion_pet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='es_mestizo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto_url',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nombre_pet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tamanio',
            field=models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='pet',
            table=None,
        ),
    ]
