# Generated by Django 5.2.8 on 2025-12-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0007_add_pet_fecha_nacimiento'),
        ('appsuavespets', '0007_alter_pet_options_remove_pet_alergias_and_more'),
    ]

    operations = [
    ]
