# Generated by Django 5.2.8 on 2025-12-03 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0008_merge_20251203_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.AddField(
            model_name='pet',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='id_pet',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_deleted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='numero_ficha',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet_veterinario_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
    ]
