# Generated by Django 5.2.8 on 2025-12-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0008_add_pet_alergias'),
        ('appsuavespets', '0009_alter_pet_options_remove_pet_fecha_nacimiento_and_more'),
    ]

    operations = [
    ]
