# Generated by Django 5.2.8 on 2025-12-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuavespets', '0010_merge_20251204_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidados',
            name='dosis',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
